### ISSUE TITLE
Volume over 100%

### ISSUE THREAD

**Issue by lamonda92** [pzim-devdata/volumouse#1]
Hi, really enjoying your application. I switched from windows to linux and wanted something similar to this https://www.nirsoft.net/utils/volumouse.html, so your application is the equivalent of that in the linux ecosystem.
I would like to point out that in linux mint that I use (probably in ubuntu as well) you set the max volume to the percentage you want, even above 100%, and the volume buttons of your laptop/keyboard respect that threshold. 
Your application goes above and beyond that limit, over-amplifying sometimes the output sound, thus creating distortion.
Is there's a line of code I can add to your script to fix this?
Thanks in advance for your help, and really enjoying your app.

**Comment by pzim-devdata** [comment]
Thank you so much for your encouragement.
~~You can use amixer instead of pactl.~~
~~For exemple `amixer set Master 120%`  will do a volume to 100% and no more~~
~~So if you want to inscrease untill 100% instead of~~
~~`subprocess.run("pactl set-sink-volume @DEFAULT_SINK@ +5% & pid=$!",shell=True)`~~
~~do~~
~~`subprocess.run("amixer set Master 5%+ & pid=$!",shell=True)`~~
~~Look at the old version of volumouse : https://github.com/pzim-devdata/Tools-for-Linux/tree/master/Volumouse~~
~~All is explain and choose "Volumouse_amixer_right.py" and "Volumouse_amixer_left.py" to download~~

~~Type `amixer -h` for help~~

~~I hope it will help :-)~~

**Comment by pzim-devdata** [comment]
Try this file, I have made this just for you : 
I have added lines 529,530, 548,549, 564,565, 580,581 if you want to check the code.
Simply extract it and replace  `volumouse.py` in your destination folder
[volumouse.py.zip](https://github.com/pzim-devdata/volumouse/files/11415827/volumouse.py.zip)

Don't forget to give me a star :1st_place_medal:

**Comment by lamonda92** [comment]
Sure thing, thanks man you're the best!

**Comment by pzim-devdata** [comment]
I have published a new version on Github with the ability to configure max volume for each card with `python3 volumouse.py -c`
Thank you for the idea ! ;-)
